#CircleCI Configuration
version : 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
        - checkout 
        
        - run:
            name: Install dotnet dependencies
            command: dotnet restore
        - run:
            name: Build
            command: dotnet build
        - run:
            name: trx Tool
            command: dotnet tool install -g trx2junit
        - run:
            name: "Run Application Tests"
            command: dotnet test -v n --logger "trx;LogFileName=test_results.trx"
        - run:
            name: "trx convert"
            command: trx2junit test_results.trx --output ../results
        - store_test_results:
            path: results


 

workflows:
  test_and_build:
    jobs:
      - build

