#CircleCI Configuration
version : 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
        - checkout 
        
        - run: dotnet restore
        - run: dotnet build
        - run: dotnet tool install -g trx2junit
        - run: dotnet test --no-build --logger "trx"
        - run: echo 'export PATH="$PATH:/root/.dotnet/tools"' >> "$BASH_ENV"
        - run: trx2junit SimCParserTests/**/TestResults/*.trx
        - store_test_results:
            path: SimCParserTests/TestResults


 

workflows:
  test_and_build:
    jobs:
      - build

