#CircleCI Configuration
version : 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
       - checkout 
       
       - run:
         name: Restore NuGet Packages
         command: dotnet restore

       - run:
          name: "Build Application according to some given configuration"
          command: dotnet build --configuration Debug
workflows:
  test_and_build:
    jobs:
      - build

