#CircleCI Configuration
version : 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
        - checkout 
        
        - run:
            name: Install dotnet dependencies
            command: restore
        - run:
            name: Build
            command: dotnet build


 

workflows:
  test_and_build:
    jobs:
      - build

