#CircleCI Configuration
version : 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
        - checkout 
        
        - run:
            name: Install dotnet dependencies
            command: dotnet restore
        - run:
            name: Build
            command: dotnet build
        - run:
            name: "Run Application Tests"
            command: dotnet test -v n --results-directory:test_coverage --collect:"Code Coverage"


 

workflows:
  test_and_build:
    jobs:
      - build

